packageExtensions:
  'eslint-module-utils@*':
    peerDependencies:
      eslint-import-resolver-node: '*'
  'eslint-config-airbnb-typescript@*':
    peerDependencies:
      eslint: '*'
      eslint-plugin-import: '*'
      eslint-plugin-jsx-a11y: '*'
      eslint-plugin-react-hooks: '*'
      eslint-plugin-react: '*'
  'gatsby-plugin-image@*':
    dependencies:
      '@babel/template': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.cjs
