packageExtensions:
  sass-loader@*:
    optionalDependencies:
      node-sass: '*'
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-berry.cjs

# Sadly a lot of things like intellisense don't seem to work with pnp :(
nodeLinker: 'node-modules'
